runtime: python
env: flex
entrypoint: gunicorn -b :$PORT --worker-class eventlet -w 1 main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

network:
  forwarded_ports:
    - 5000
  session_affinity: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app